[package]
authors = [
  "Jorge Aparicio <jorge@japaric.io>",
  "Per Lindgren <per.lindgren@ltu.se>",
]
categories = [
    "data-structures",
    "no-std",
]
description = "`static` friendly data structures that don't require dynamic memory allocation"
documentation = "https://docs.rs/heapless"
edition = "2018"
keywords = [
    "static",
    "no-heap",
]
license = "MIT OR Apache-2.0"
name = "heapless"
repository = "https://github.com/japaric/heapless"
version = "0.6.1"

[features]
default = ["cas"]
cas = []
ufmt-impl = ["ufmt-write"]
# read the docs before enabling: makes `Pool` Sync on x86_64
x86-sync-pool = []
# only for tests
__trybuild = []

[target.x86_64-unknown-linux-gnu.dev-dependencies]
scoped_threadpool = "0.1.8"

[dependencies]
as-slice = "0.1.5"
generic-array = "0.14.4"
hash32 = "0.1.0"

[dependencies.serde]
version = "1"
optional = true
default-features = false

[dependencies.stable_deref_trait]
version = "1"
default-features = false

[dependencies.ufmt-write]
version = "0.1"
optional = true

[dev-dependencies.ufmt]
version = "0.1"
